# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.4.5, generator: @autorest/python@5.8.3)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AuthenticationMechanism
    from ._models_py3 import Device
    from ._models_py3 import DeviceCapabilities
    from ._models_py3 import FileUploadCompletionStatus
    from ._models_py3 import FileUploadRequest
    from ._models_py3 import FileUploadResponse
    from ._models_py3 import Module
    from ._models_py3 import ScopeResult
    from ._models_py3 import SymmetricKey
    from ._models_py3 import X509Thumbprint
except (SyntaxError, ImportError):
    from ._models import AuthenticationMechanism  # type: ignore
    from ._models import Device  # type: ignore
    from ._models import DeviceCapabilities  # type: ignore
    from ._models import FileUploadCompletionStatus  # type: ignore
    from ._models import FileUploadRequest  # type: ignore
    from ._models import FileUploadResponse  # type: ignore
    from ._models import Module  # type: ignore
    from ._models import ScopeResult  # type: ignore
    from ._models import SymmetricKey  # type: ignore
    from ._models import X509Thumbprint  # type: ignore

from ._iot_hub_gateway_device_apis_enums import (
    AuthenticationMechanismType,
    DeviceConnectionState,
    DeviceStatus,
    ModuleConnectionState,
)

__all__ = [
    'AuthenticationMechanism',
    'Device',
    'DeviceCapabilities',
    'FileUploadCompletionStatus',
    'FileUploadRequest',
    'FileUploadResponse',
    'Module',
    'ScopeResult',
    'SymmetricKey',
    'X509Thumbprint',
    'AuthenticationMechanismType',
    'DeviceConnectionState',
    'DeviceStatus',
    'ModuleConnectionState',
]
